cleanup
placeAtlas/atlas pull request #1145
Opened 2022-04-09 12:26 UTC by babyhuehnchen

removed a few duplicates, obsolete/low quality/non-englisch entries and a few entries containing zalgo

2022-04-09 16:35 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "twu16a", "submitted_by": "Prudent-Ad5308", "name": "Daft Punk x PNL", "description": "This art is a mix between PNL's album 'Deux frères' and Daft Punk's masks. These two artists are the bigg
This entry has no duplicate and is valid for a previous version of the canvas.

2022-04-09 16:39 UTC, AnonymousRandomPerson requested changes
Resolve pending comments.

2022-04-09 16:39 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "tx2yh3", "submitted_by": "TropicalTwister1", "name": "KEL", "description": "KEL is one of the deuteragonists in OMORI. He was relocated multiple times, and his existence can be debated as he
This entry is valid for a previous version of the canvas.

2022-04-09 16:39 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "tx2s1p", "submitted_by": "Alin_Alexandru", "name": "Second Romanian flag", "description": "The second Romanian flag which featured Brâncuși's Endless Columnn, as well as Spider Man and Miles
This entry is valid for a previous version of the canvas.

2022-04-09 16:39 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "tx63kh", "submitted_by": "link_dead", "name": "2B butt censorship", "description": "During an incursion into the French-controlled corner. North American Twitch streamers xQc and Mizkif deplo
This is a valid historical event on the canvas.

2022-04-09 16:39 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "tyk6ov", "submitted_by": "Andyangel98", "name": "First Romanian Flag", "description": "First Romanian Flag. It was replaced with Polish Flag in the end. The flag contained the Romanian coat o
This entry is valid for a previous version of the canvas.

2022-04-15 13:25 UTC, ab-gh commented
This PR has been closed. Please reopen when you make the required changes.

2022-04-15 13:25 UTC, closed without merging