Update atlas.json
placeAtlas/atlas pull request #1263
Opened 2022-04-12 20:24 UTC by Grymtn12

Removed extra entries for rickroll qr code(originally there was 3 which wasn't added by any admin of our community).

Changed the description of the last one left to our preferred one. Also since the qr code is already going to youtube link we have changed link in to our community discord invite link.

One of the removed entries was from another subreddit(r/placeQRcode) which didn't belong to us. We dont have a subreddit.

2022-04-12 20:33 UTC, Codixer commented
Resolve the conflict

2022-04-13 00:55 UTC, Grymtn12 commented
How do i actually resolve this, only thing i did is edit the atlas.json file and upload it, i removed the two lines that was saying rickrollqr and i edited the last one left, sorry im new to github

2022-04-13 02:03 UTC, AnonymousRandomPerson commented
If you're not familiar with resolving merge conflicts and looking up tutorials doesn't help, a more crude option is to delete/reclone the repo and redo your changes.

2022-04-13 02:06 UTC, AnonymousRandomPerson commented on web/atlas.json
> -{"id": "tx0p3o", "submitted_by": "AustinQ", "name": "Rick Roll QR Code", "description": "While it doesn't appear in this screencap, the Rick Roll QR Code was rebuilt here just a couple minutes before
I see discussion on r/placeQRcode about these coordinates. Even if your group did not communicate with them, it looks like they independently contributed. All parties should be credited, so keep that subreddit in the remaining non-duped entries.

2022-04-13 02:06 UTC, AnonymousRandomPerson requested changes
Address comments and merge conflicts.

2022-04-13 03:54 UTC, Grymtn12 commented
updated the json file to include the r/placeQRcode, didnt change any other entry about rickroll except for the top one to the said updated on first request

2022-04-13 06:53 UTC, AnonymousRandomPerson commented
Your PR now shows a ton of changes. I don't think that's intended?

2022-04-13 07:08 UTC, Grymtn12 commented
it should be only one line thats changed maybe i copypasted wrong the id tharts changed is twny3k at 472 that line only.

2022-04-15 13:24 UTC, closed without merging