Deleted duplicate Dart Monkey atlas entry
placeAtlas/atlas pull request #1307
Opened 2022-04-15 10:03 UTC by VortexVirtue

2022-04-15 13:21 UTC, ab-gh commented on web/atlas.json
> +{"id": "twlese", "submitted_by": "KirbeTheEngineer", "name": "Dart Monkey (BTD6)", "description": "The Dart Monkey is a tower from the tower defense game Bloons Tower Defense, namely the sixth mainli
```suggestion
{"id": "twlese", "submitted_by": "KirbeTheEngineer", "name": "Dart Monkey (BTD6)", "description": "The Dart Monkey is a tower from the tower defense game Bloons Tower Defense, namely the sixth mainline installment, Bloons Tower Defense 6.", "website": "https://ninjakiwi.com", "subreddit": "/r/btd6", "center": [1877.5, 1656.5], "path": [[1886.5, 1679.5], [1872.5, 1679.5], [1872.5, 1669.5], [1863.5, 1669.5], [1863.5, 1665.5], [1872.5, 1663.5], [1863.5, 1659.5], [1863.5, 1644.5], [1870.5, 1638.5], [1874.5, 1637.5], [1875.5, 1634.5], [1878.5, 1633.5], [1882.5, 1635.5], [1884.5, 1638.5], [1884.5, 1640.5], [1887.5, 1648.5], [1890.5, 1650.5], [1890.5, 1654.5], [1884.5, 1658.5], [1885.5, 1666.5], [1896.5, 1665.5], [1900.5, 1671.5], [1897.5, 1673.5], [1896.5, 1671.5], [1896.5, 1668.5], [1883.5, 1669.5]]},

```

2022-04-15 13:22 UTC, ab-gh requested changes

2022-04-15 13:22 UTC, ab-gh commented on web/atlas.json
> +{"id": "twlese", "submitted_by": "KirbeTheEngineer", "name": "Dart Monkey (BTD6)", "description": "The Dart Monkey is a tower from the tower defense game Bloons Tower Defense, namely the sixth mainli
Please ensure submissions contain valid JSON

2022-04-24 19:37 UTC, AnonymousRandomPerson commented
I incorporated this change myself.

2022-04-24 19:37 UTC, closed without merging