Node.js tool for detecting Entries that share 99% of their area (Duplicates)
placeAtlas/atlas pull request #576
Opened 2022-04-05 23:04 UTC by DRKSLV

Hi, i made a handy tool for getting a list of duplicates

Assigns duplicates based on Polygons: `intersec_area/outer_area < 0.01`
Almost no false positives, quite a few false negatives when borders of duplicate are drawn sloppily

The script also generates a second version of the atlas:
Adds parent: "" property to the atlas, that lists the id of the first identical element
Adds bounds: [] property with bounding box
Adds childs: [] property with the ids of the children
(These properties could be used to fold all duplicates in a comment section style below the parent entry, so they don't take up space)

To run, download Node.js and run `node tools/duplicateFinder`

2022-04-05 23:55 UTC, DRKSLV commented
Oop, i'll have to fix this tomorrow, but it seems that the vertex order of the intersected polygon is wrong, and could throw off area calculations
This is because i accidentally implemented the convex version of the intersection algorithm
The concave one requires an additional step to determine the vertex order

Also in line 24 i call orderClockwise on the input polygon
i think that again has the catch of messing up concave polygons 
(that only throws off the area calculation, as the modified polygon isn't written to the file, but its definetely bad)

so i'll have to fix some of that stuff tomorrow, sorry guys :(

2022-04-06 02:02 UTC, nathanfranke requested changes
Note: I am not a maintainer of this repository.

2022-04-06 02:02 UTC, nathanfranke commented on web/_js/pointInPolygon.js
> +    module.exports = pointIsInPolygon;
```suggestion

// for use in node.js tooling
if (typeof window == "undefined") {
    module.exports = pointIsInPolygon;
}
```

Include a trailing newline to be [POSIX compliant](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

2022-04-06 02:02 UTC, nathanfranke commented on tools/duplicateFinder.js
> +console.log( doBoundsCollide( [ 0, 0, 2, 2 ], [0, -2.01, 2, 2] ))*/
Include a trailing newline to be [POSIX compliant](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline).

2022-04-06 05:41 UTC, DRKSLV commented on web/_js/infoblock.js
> -    idElement.innerText = "id: " + entry.id;
I had previously had a change here and removed it
A semicolon was left over from my tampering

I can remove it for clarity but the line has to stay

2022-04-06 23:29 UTC, DRKSLV commented
Hi, good and bad news
i had a little less time today,
and unfortunately hit a 2h+ dead end trying to understand the "Weiler Atherton"-Algorithm.
Mostly because i was learning from the ramblings of a paranoid scizophrenic on stack overflow with 0 upvotes,
instead of taking the 5minutes to find an actual resource...

Good news: I am on track now and it's a lot less complicated than SO makes it seem, so i'm probably going to reach an acceptable state soon, where ppl can already use the tool to manually find duplicates, and then it may or may not be integrated further, depending on the projects needs and yalls opinion

2022-04-06 23:34 UTC, DRKSLV commented
Currently there is a problem with edge cases, when points of one polygon are placed exactly on top of lines of the other polygon
This is unfortunately very common and results in errors such as the GME line being classified as a duplicate of the "dutch right region", due to the intersection polygon being way larger than it should be
This is obviously unacceptable, an i'll try to work on it further tomorrow

Apparently, intersection points need to be classified by "entering", "exiting" and "not actually an intersection lmao this is cursed"
Currently, this just causes broken polygons

I'll try to get to it tomorrow

2022-04-06 23:36 UTC, DRKSLV commented
Ah, and heads up!
The code is currently not even doing it's main task, instead it's running tests, that i manually comment and uncomment

This will all be removed if and when this is ready to merge

2022-04-07 18:20 UTC, ProstoSanja commented
Can you please mark the PR as draft until its done?

2022-05-14 02:38 UTC, AnonymousRandomPerson commented
This appears to be inactive. I'll close this PR; feel free to reopen if you'd still like to contribute this.

2022-05-14 02:38 UTC, closed without merging

2022-05-14 09:19 UTC, DRKSLV commented
Fair: sorry i really got overwhelmed with some unexpected stuff

Maybe ill resume work on this later